obj-$(CONFIG_MWLWIFI)	+= mwlwifi.o

mwlwifi-objs		+= mwl_main.o
mwlwifi-objs		+= mwl_mac80211.o
mwlwifi-objs		+= mwl_fwdl.o
mwlwifi-objs		+= mwl_fwcmd.o
mwlwifi-objs		+= mwl_tx.o
mwlwifi-objs		+= mwl_rx.o
mwlwifi-objs		+= mwl_debug.o
